# Generated by Django 6.0 on 2025-12-19 01:57

import django.db.models.deletion
import oficio.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnteDevedor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(help_text='Ex: Fazenda Pública do Estado de São Paulo', max_length=255)),
                ('cnpj', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('esfera', models.CharField(choices=[('Federal', 'Federal'), ('Estadual', 'Estadual'), ('Municipal', 'Municipal')], max_length=20)),
            ],
            options={
                'verbose_name': 'Ente Devedor',
                'verbose_name_plural': 'Entes Devedores',
                'db_table': 'entes_devedores',
            },
        ),
        migrations.CreateModel(
            name='Tribunal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(help_text='Ex: Tribunal Regional Federal da 1ª Região', max_length=150, unique=True)),
                ('sigla', models.CharField(help_text='Ex: TRF1', max_length=20, unique=True)),
                ('uf', models.CharField(blank=True, help_text='Estado do tribunal', max_length=2, null=True)),
            ],
            options={
                'verbose_name': 'Tribunal',
                'verbose_name_plural': 'Tribunais',
                'db_table': 'tribunais',
                'ordering': ['sigla'],
            },
        ),
        migrations.CreateModel(
            name='Precatorio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_processo', models.CharField(help_text='Número CNJ ou do Ofício Requisitório', max_length=50, unique=True)),
                ('natureza', models.CharField(choices=[('Alimentar', 'Alimentar'), ('Comum', 'Comum')], max_length=20)),
                ('valor_principal', models.DecimalField(decimal_places=2, help_text='Valor de face do precatório', max_digits=18)),
                ('valor_venda', models.DecimalField(blank=True, decimal_places=2, help_text='Valor pretendido para venda', max_digits=18, null=True)),
                ('percentual_honorarios', models.DecimalField(decimal_places=2, default=0, help_text='Percentual de honorários contratuais destacadados', max_digits=5)),
                ('data_expedicao', models.DateField(help_text='Data de expedição do ofício')),
                ('ano_orcamentario', models.IntegerField(help_text='Ano do orçamento para pagamento')),
                ('status', models.CharField(choices=[('Em Análise', 'Em Análise'), ('Disponível', 'Disponível'), ('Em Negociação', 'Em Negociação'), ('Vendido', 'Vendido'), ('Suspenso', 'Suspenso')], default='Em Análise', max_length=20)),
                ('descricao', models.TextField(blank=True, help_text='Observações gerais sobre o ativo', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('advogado', models.ForeignKey(blank=True, limit_choices_to={'type_user': 'Advogado'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='precatorios_advogado', to=settings.AUTH_USER_MODEL)),
                ('cedente', models.ForeignKey(help_text='O dono original do título', limit_choices_to={'type_user': 'Cedente'}, on_delete=django.db.models.deletion.PROTECT, related_name='precatorios_cedente', to=settings.AUTH_USER_MODEL)),
                ('ente_devedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oficio.entedevedor')),
                ('tribunal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oficio.tribunal')),
            ],
            options={
                'verbose_name': 'Precatório',
                'verbose_name_plural': 'Precatórios',
                'db_table': 'precatorios',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(help_text='Ex: Ofício Requisitório, Memória de Cálculo', max_length=100)),
                ('arquivo', models.FileField(help_text='Apenas arquivos PDF (.pdf) e Word (.doc, .docx) são aceitos. Tamanho máximo: 10MB', upload_to='precatorios/docs/%Y/%m/', validators=[oficio.models.validate_file_extension, oficio.models.validate_file_size])),
                ('enviado_em', models.DateTimeField(auto_now_add=True)),
                ('precatorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='oficio.precatorio')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'db_table': 'precatorios_documentos',
                'ordering': ['-enviado_em'],
            },
        ),
        migrations.AddIndex(
            model_name='precatorio',
            index=models.Index(fields=['numero_processo'], name='precatorios_numero__a377e5_idx'),
        ),
        migrations.AddIndex(
            model_name='precatorio',
            index=models.Index(fields=['status'], name='precatorios_status_2f6685_idx'),
        ),
        migrations.AddIndex(
            model_name='precatorio',
            index=models.Index(fields=['natureza'], name='precatorios_naturez_6e0201_idx'),
        ),
        migrations.AddIndex(
            model_name='precatorio',
            index=models.Index(fields=['ano_orcamentario'], name='precatorios_ano_orc_064c59_idx'),
        ),
    ]
