# Generated by Django 6.0 on 2026-01-15 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oficio", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="precatorio",
            name="broker",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"type_user": "Broker"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="precatorios_broker",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
