# Generated by Django 6.0 on 2025-12-22 17:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('oficio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('valor_proposto', models.DecimalField(decimal_places=2, max_digits=18)),
                ('taxa_desconto', models.DecimalField(decimal_places=2, max_digits=5)),
                ('taxa_juros_anual', models.DecimalField(decimal_places=2, max_digits=5)),
                ('prazo_pagamento_meses', models.IntegerField()),
                ('valor_liquido_cedente', models.DecimalField(decimal_places=2, max_digits=18)),
                ('valor_liquido_proponente', models.DecimalField(decimal_places=2, max_digits=18)),
                ('margem_lucro_percentual', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.CharField(choices=[('RASCUNHO', 'rascunho'), ('ENVIADA', 'enviada'), ('ACEITA', 'aceita'), ('REJEITADA', 'rejeitada'), ('EXPIRADA', 'expirada')], default='RASCUNHO', max_length=20)),
                ('data_vencimento', models.DateField()),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('precatorio', models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.PROTECT, to='oficio.precatorio')),
                ('proponente', models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProposalHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status_anterior', models.CharField(choices=[('RASCUNHO', 'rascunho'), ('ENVIADA', 'enviada'), ('ACEITA', 'aceita'), ('REJEITADA', 'rejeitada'), ('EXPIRADA', 'expirada')], default='RASCUNHO', max_length=20)),
                ('status_novo', models.CharField(choices=[('RASCUNHO', 'rascunho'), ('ENVIADA', 'enviada'), ('ACEITA', 'aceita'), ('REJEITADA', 'rejeitada'), ('EXPIRADA', 'expirada')], default='ENVIADA', max_length=20)),
                ('valor_anterior', models.DecimalField(decimal_places=2, max_digits=18)),
                ('valor_novo', models.DecimalField(decimal_places=2, max_digits=18)),
                ('motivo_alteracao', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alterado_por', models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('proposal', models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.PROTECT, to='proposal.proposal')),
            ],
        ),
    ]
