# Generated by Django 6.0 on 2025-12-22 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proposal", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proposalhistory",
            name="proposal",
            field=models.ForeignKey(
                max_length=255,
                on_delete=django.db.models.deletion.CASCADE,
                to="proposal.proposal",
            ),
        ),
    ]
