"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
from datetime import timedelta
from pathlib import Path
from decouple import AutoConfig

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

config = AutoConfig(search_path=BASE_DIR)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-k2$_)e47$vp*!=uvlnb_vgpj+eg^*--dx(s*!okn#er57aj*8t'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
]
APPEND_SLASH = True

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'auth.apps.AuthConfig', 
    'drf_spectacular',
    'oficio.apps.OficioConfig',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "HOST": config("DB_HOST", default="localhost"),
        "PORT": config("DB_PORT", default="5433"),
        "NAME": config("DB_NAME", default="lexpay"),
        "USER": config("DB_USER", default="lexpay"),
        "PASSWORD": config("DB_PASSWORD", default="lexpay"),
        "OPTIONS": {
            "connect_timeout": 10,
        },
        "ATOMIC_REQUESTS": True,
    },
}



# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = "America/Recife"

USE_I18N = True

USE_TZ = True

AUTH_USER_MODEL = 'auth_app.User' 


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
MEDIA_ROOT = BASE_DIR / 'media'
MEDIA_URL = '/media/'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DATE_FORMAT': "%d-%m-%Y",
    'DATETIME_FORMAT': "%d-%m-%Y %H:%M",
    'DATE_INPUT_FORMATS': ["%d-%m-%Y"],
    'DATETIME_INPUT_FORMATS': ["%d-%m-%Y %H:%M"],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=24),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=8),
    "CANCEL_TOKEN_LIFETIME": timedelta(days=15),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "ALGORITHM": "HS256",
    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'LexPay',
    'DESCRIPTION': 'Esta é a documentação da API LexPay, um sistema de gerenciamento de precatórios e pagamentos inspirados no Celer..',
    'VERSION': '1.0.0',
    'TERMS_OF_SERVICE': 'github.io//RobsonFe',
    'CONTACT': {
        'name': 'Robson Ferreira',
        'email': 'robsonfe.dev@gmail.com',
    },
    'LICENSE': {
        'name': 'EULA License',
        'url': 'https://www.eula.com',
    },
    'SCHEMA_COERCE_PATH_PK_SUFFIX': True,
    'TAGS': [
        {'name': 'Autenticação', 'description': 'Configurações referentes à autenticação do sistema'},
        {'name': 'Usuário', 'description': 'Configurações referentes aos usuários do sistema'},
        {'name': 'Endereço', 'description': 'Configurações referentes aos endereços do sistema'},
        {'name': 'Precatórios', 'description': 'Configurações referentes aos precatórios do sistema'},
    ],
    'SORT_OPERATIONS': False,
    'ENUM_NAME_OVERRIDES': {},
    'SCHEMA_PATH_PREFIX': '/api/v1',
    'ENUM_GENERATE_CHOICE_DESCRIPTION': True,
    'ENUM_SUFFIX': 'Type',
    'POSTPROCESSING_HOOKS': [
        'hook.allowed_tags.filter_endpoints_by_allowed_tags',
    ],
    "SERVE_PERMISSIONS": ["rest_framework.permissions.AllowAny"],
    'SERVE_INCLUDE_SCHEMA': True,
    "COMPONENT_SPLIT_REQUEST": False,
}