# Generated by Django 6.0 on 2025-12-18 14:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('avatar', models.ImageField(blank=True, default='avatars/default.png', help_text='Avatar do usuário', null=True, upload_to='avatars/')),
                ('username', models.CharField(help_text='Username do usuário', max_length=100, unique=True)),
                ('name', models.CharField(blank=True, help_text='Nome completo do usuário', max_length=100, null=True)),
                ('email', models.EmailField(help_text='Email do usuário', max_length=255, unique=True)),
                ('cpf', models.CharField(blank=True, help_text='CPF do usuário', max_length=11, null=True, unique=True)),
                ('phone', models.CharField(blank=True, help_text='Telefone do usuário', max_length=11, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Designa se este usuário deve ser tratado como ativo.')),
                ('is_staff', models.BooleanField(default=False, help_text='Designa se o usuário pode acessar o site de administração.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data de atualização')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'db_table': 'users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address', models.CharField(blank=True, help_text='Endereço do usuário', max_length=255, null=True)),
                ('number', models.CharField(blank=True, help_text='Número do endereço', max_length=10, null=True)),
                ('complement', models.CharField(blank=True, help_text='Complemento do endereço', max_length=255, null=True)),
                ('city', models.CharField(blank=True, help_text='Cidade do endereço', max_length=255, null=True)),
                ('state', models.CharField(blank=True, help_text='Estado do endereço', max_length=2, null=True)),
                ('zip_code', models.CharField(blank=True, help_text='CEP do endereço', max_length=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data de atualização')),
                ('user', models.ForeignKey(help_text='Usuário do endereço', on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Endereço',
                'verbose_name_plural': 'Endereços',
                'db_table': 'addresses',
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='users_email_4b85f2_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username'], name='users_usernam_baeb4b_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['cpf'], name='users_cpf_15510e_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['phone'], name='users_phone_af6883_idx'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['city'], name='addresses_city_dfd875_idx'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['state'], name='addresses_state_065a3c_idx'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['zip_code'], name='addresses_zip_cod_610cec_idx'),
        ),
    ]
