# Generated by Django 6.0 on 2025-12-18 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='zip_code',
            field=models.CharField(blank=True, help_text='CEP do endereço', max_length=10, null=True),
        ),
    ]
