# Generated by Django 6.0 on 2025-12-18 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('auth_app', '0002_alter_address_zip_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type_user',
            field=models.CharField(choices=[('Cedente', 'Cedente'), ('Broker', 'Broker'), ('Administrador', 'Administrador'), ('Advogado', 'Advogado')], default='Broker', help_text='Tipo de usuário', max_length=20),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['type_user'], name='users_type_us_3a9c90_idx'),
        ),
    ]
