# Generated by Django 6.0 on 2025-12-19 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_user_type_user_user_users_type_us_3a9c90_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cpf',
            field=models.CharField(blank=True, help_text='CPF do usuário', max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, help_text='Telefone do usuário', max_length=20, null=True, unique=True),
        ),
    ]
