# Generated by Django 6.0 on 2025-12-19 18:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('oficio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DueDiligence',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('status_analise', models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_ANALISE', 'Em analise'), ('APROVADO', 'Aprovado'), ('REPACTUADO', 'Repactuado'), ('REJEITADO', 'Rejeitado')], db_index=True, default='PENDENTE')),
                ('data_inicio_analise', models.DateField()),
                ('data_conclusao_analise', models.DateField()),
                ('observacoes', models.TextField()),
                ('documento_aprovado', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analista', models.ForeignKey(limit_choices_to={'tipy_user__in': ['Broker', 'Administrador']}, on_delete=django.db.models.deletion.PROTECT, related_name='usuario', to=settings.AUTH_USER_MODEL)),
                ('precatorio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='precatorio', to='oficio.precatorio')),
            ],
        ),
    ]
