# Generated by Django 6.0 on 2025-12-19 19:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('oficio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DueDiligence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status_analise', models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_ANALISE', 'Em Análise'), ('APROVADO', 'Aprovado'), ('REPACTUADO', 'Repactuado'), ('REJEITADO', 'Rejeitado')], db_index=True, default='PENDENTE', max_length=20)),
                ('data_inicio_analise', models.DateTimeField(blank=True, null=True)),
                ('data_conclusao_analise', models.DateTimeField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('documento_aprovado', models.BooleanField(default=False)),
                ('motivo_repactuacao', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analista', models.ForeignKey(help_text='Responsável pela análise (Apenas Admin ou Broker)', limit_choices_to={'type_user__in': ['Broker', 'Administrador']}, on_delete=django.db.models.deletion.PROTECT, related_name='analises_realizadas', to=settings.AUTH_USER_MODEL)),
                ('precatorio', models.ForeignKey(help_text='Precatório que está sendo analisado', on_delete=django.db.models.deletion.PROTECT, related_name='diligencias', to='oficio.precatorio')),
            ],
            options={
                'verbose_name': 'Due Diligence',
                'verbose_name_plural': 'Due Diligences',
                'db_table': 'due_diligences',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status_analise', 'REJEITADO'), _negated=True), fields=('precatorio',), name='unique_active_due_diligence')],
            },
        ),
    ]
