# Generated by Django 6.0 on 2026-01-06 13:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("due", "0002_analisedocumento"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="analisedocumento",
            name="analisado_por",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="analisado_por",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
