# Generated by Django 6.0 on 2026-01-12 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("due", "0004_alter_analisedocumento_analisado_por_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="duediligence",
            name="prioridade",
            field=models.CharField(
                choices=[("BAIXA", "Baixa"), ("MEDIA", "Média"), ("ALTA", "Alta")],
                db_index=True,
                default="MEDIA",
                max_length=10,
            ),
        ),
    ]
