# Generated by Django 6.0 on 2026-01-15 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("due", "0005_duediligence_prioridade"),
    ]

    operations = [
        migrations.AlterField(
            model_name="duediligence",
            name="prioridade",
            field=models.CharField(
                choices=[("BAIXA", "Baixa"), ("MEDIA", "Media"), ("ALTA", "Alta")],
                db_index=True,
                default="MEDIA",
                max_length=10,
            ),
        ),
    ]
